---
output:
  html_document:
    self_contained: no
    smart: no
    css: styles.css
runtime: shiny
---
```{r, echo=FALSE}
invisible(library(stats));
source("./cdc_model_functions.R")
source("./cdc_plotting_functions.R")
```

### Results

```{r run, echo=FALSE}
res <- reactive({
  simulate(list(
    infective_treatments = defaults$infective_treatments,
    treatment_durations = treatment_durations(),
    simulation_duration = simulation_duration(),
    treatment_distribution = yield_intervention(intervention_scenario()),
    introductions = yield_introduction(introduction_scenario()), 
    treatment_transmissions = treatment_transmissions(),
    hosp_proportions = treatment_demands(),
    E_day_PDF = distros$inc()$pdf,
    I_day_PDF = distros$inf()$pdf,
    N0 = N0()
  ))
})
tabsetPanel(
  tabPanel("Cumulative Incidence",
    renderPlot({
      plotCumInc(res(), start=input$start_date, reporting_rate=input$reporting_rate)
    })
  ),
  tabPanel("Bed Occupancy",
    renderPlot({
      plotBedOcc(res(), start=input$start_date, reporting_rate=input$reporting_rate) 
    })
  )
)
```

### Model Settings

```{r disease_params, echo=FALSE}
absolute_pdf_day_max <- 60
manualPDF <- function(prefix) {
  lapply(
    1:absolute_pdf_day_max,
    function(day) conditionalPanel(
      paste0("input.",prefix,"_period_max >= ",day),
      numericInput(paste0(prefix, "_pdf_", day), day, 0, min=0, max=1, step=0.0001)
    )
  )
}
buildPDFPanel <- function(prefix, full,
  def_period_max,
  def_model,
  def_period_mean,
  def_period_sd,
  choices
) {
  sum_check_id <- paste0(prefix,"_pdf_sum")
  output[[sum_check_id]] <- renderText(sum(distros[[prefix]]()$pdf))
  column(4, div(class = "pdf",
    h4(full," Period"),
    numericInput(
      paste0(prefix,"_period_max"),
      "max",
      min=1, max=absolute_pdf_day_max, value=def_period_max, step=1
    ), em("(days)"),
    conditionalPanel("input.pdf_type == 'manual'",
      div(tags$label("day"), em("p")," (total: ",textOutput(sum_check_id, em),")"),
      manualPDF(prefix)
    ),
    conditionalPanel("input.pdf_type === 'functional'",
      div(selectInput(
        paste0(prefix,"_model"),
        "distribution",
        choices=choices, selected=def_model
      )),
      conditionalPanel(paste0("(input.", prefix, "_model === '", choices[1], "') || (input.", prefix, "_model === '", choices[2], "')"),
        div(numericInput(
          paste0(prefix,"_period_mean"),
          "mean",
          min=0.01, max=25, value=def_period_mean, step=0.01
        ), em("(days)")),
        div(numericInput(
          paste0(prefix,"_period_sd"),
          "std.dev.",
          min=0.01, max=25, value=def_period_sd, step=0.01
        ), em("(days)"))
      )
    )
  ))
}
buildTreatmentCol <- function(prefix, defs, step, max, treatments = defaults$infective_treatments) {
  mapply(function(id, label, def) numericInput(id, label, min=0, step=step, max=max, value=def),
    paste0(prefix, names(treatments)),
    treatments,
    defs,
    SIMPLIFY=F
  )
}
absolute_max_events <- 50
interventionInputs <- function() {
  lapply(
    1:absolute_max_events,
    function(id) conditionalPanel(
      paste0("input.intervention_event_max >= ",id),
      numericInput(paste0("treatment_day_", id), "Day", value=id, min=id, step=1),
      sliderInput(paste0("treatment_pro_", id), "Allocations", value=c(0,0.05), min=0, max=1, step=0.01)
    )
  )
}
buildInterventionCol <- function() {
  column(4,
    numericInput(
      "intervention_event_max",
      "Changes in Treatment Allocation?",
      min=1, max=absolute_max_events, value=1, step=1
    ),
    interventionInputs()
  )
}
intervention_scenario <- reactive({
  max_events <- input$intervention_event_max
  validate(need(!is.null(max_events), "max duration not initialized."))
  res <- {
    labels <- paste0("treatment_pro_", 1:max_events)
    day_labels <- paste0("treatment_day_", 1:max_events)
    validate(need(!is.null(input[[tail(labels, 1)]]), "Awaiting intervention inputs."))
    temp <- mapply(function(day, data) {
      pro <- input[[data]]
      hosp_pro <- pro[1]
      home_pro <- pro[2]-pro[1]
      none_pro <- 1 - pro[2]
      return(c(input[[day]], hosp_pro, home_pro, none_pro))
    }, day_labels, labels, USE.NAMES=F)
    res <- data.frame(t(temp))
    names(res) <- c("start_day","Hospitalized","Isolating Home Care","Other Care")
    res
  }
})
introductionInputs <- function() {
  lapply(
    1:absolute_max_events,
    function(id) conditionalPanel(
      paste0("input.introduction_event_max >= ",id),
      numericInput(paste0("intro_day_", id), "Day", value=id, min=id, step=1),
      numericInput(paste0("intro_count_", id), "Introductions", value=25, min=1, step=1)
    )
  )
}
buildIntroductionCol <- function() {
  column(4,
    numericInput(
      "introduction_event_max",
      "Introduction Events?",
      min=1, max=absolute_max_events, value=1, step=1
    ),
    introductionInputs()
  )
}
introduction_scenario <- reactive({
  max_events <- input$introduction_event_max
  validate(need(!is.null(max_events), "max duration not initialized."))
  res <- {
    labels <- paste0("intro_count_", 1:max_events)
    day_labels <- paste0("intro_day_", 1:max_events)
    validate(need(!is.null(input[[tail(labels, 1)]]), "Awaiting introduction inputs."))
    temp <- mapply(function(day, data) {
      return(c(input[[day]], input[[data]]))
    }, day_labels, labels, USE.NAMES=F)
    res <- data.frame(t(temp))
    names(res) <- c("day","count")
    res
  }
})

with(defaults, {
  inputPanel(tabsetPanel(
    tabPanel("General Parameters", div(class="gen",
      numericInput("N0","Initial Population (millions)?", value=N0/10^6, min=0.01, max=100, step=0.01),
      numericInput("simulation_duration","Simulation Duration (days)?", value=simulation_duration, min=1, max=365*2, step=1),
      dateInput("start_date","Outbreak state date (yyyy-mm-dd)?", min="2014-01-01", max="2014-12-31", value="2014-02-03"),
      numericInput("reporting_rate", "Case Reporting Rate?", min=0, value = 1/2.5, step=0.001)
    )),
    tabPanel("Incubation and Infectious Distributions",
      fixedRow(column(10,
        actionButton("reset_cdc", "Set to CDC defaults."),
        actionButton("reset_leg", "Set to Legrand."),
        actionButton("reset_eic", "Set to Eichner."),
        radioButtons(
          "pdf_type",
          "Distribution Mode: ",
          choices=c("manual","functional"), selected="manual",
          inline=T
        )
      )),
      fixedRow(
        buildPDFPanel("inc", "Incubation", inc_period_max, inc_model, inc_period_mean, inc_period_sd, choices),
        buildPDFPanel("inf", "Infectious", inf_period_max, inf_model, inf_period_mean, inf_period_sd, choices)
      )
    ),
    tabPanel("Treatment-Related Parameters",
      fixedRow(
        column(3,
          h4("Infection pressure from..."),
          buildTreatmentCol('tr_rate_', defaults$treatment_transmissions, step=0.01, max=10.0)
        ),
        column(3,
          h4("Hospital bed-days for..."),
          buildTreatmentCol('tr_dur_', defaults$treatment_durations, step=1, max=absolute_pdf_day_max)
        ),
        column(3,
          h4("Hospitalized Proportion for..."),
          buildTreatmentCol('tr_prop_', defaults$hosp_proportions, step=0.01, max=1.0)
        )
      )
    ),
    tabPanel("Scenario Parameters",
      fixedRow(
        buildInterventionCol(),
        buildIntroductionCol()
      )
    ),
    tabPanel("Notes", div(
      "TODO: provide notes.  particularly, describe CDC 'distribution' computations, provide citations."
      ), div(
      "TODO: (1) turn on asymptomatic infection, (2) turn on mortality (and allow to affect governor)"
      )
    )
  ))
})
```

```{r pdfs, echo=FALSE}
buildReactiveDistro <- function(prefix) {
  ref_period_max <- paste0(prefix,"_period_max")
  pdf_base <- paste0(prefix,"_pdf_")
  ref_model <- paste0(prefix,"_model")
  ref_mean <- paste0(prefix,"_period_mean")
  ref_sd <- paste0(prefix,"_period_sd")
  return(
    reactive({
      validate(need(!is.null(input$pdf_type),"PDF type not initialized."))
      max_day <- input[[ref_period_max]]
      validate(need(!is.null(max_day), "max duration not initialized."))
      res <- if (input$pdf_type == "manual") {
        day_labels <- paste0(pdf_base, 1:max_day)
        validate(need(!is.null(input[[tail(day_labels, 1)]]), "Awaiting manual pdf construction."))
        temp <- sapply(day_labels, function(day) input[[day]])
        list(pdf=temp, cdf=c(0,cumsum(temp)), days=0:(length(temp)-1))
      } else {
        model <- input[[ref_model]]
        other_params <- switch(model,
          gamma =,
          lnorm = list(period_mean = input[[ref_mean]], period_sd = input[[ref_sd]]),
          list()
        )
        do.call(distribution, c(list(model=model, period_max=max_day), other_params) )
      }
      ressum <- sum(res$pdf)
      validate(need(ressum==1, paste0("PDF does not sum to 1: ", ressum)))
      return(res)
    })
  )
}
distros <- list(inc=buildReactiveDistro("inc"), inf=buildReactiveDistro("inf"))
treatment_parameter <- function(prefix, ...) {
  ref <- paste0(prefix, names(defaults$infective_treatments))
  names(ref) <- names(defaults$infective_treatments)
  return(reactive({
    res <- sapply(ref, function(what) input[[what]])
    validate(need(all(!sapply(res, is.null)), paste0(prefix," info incomplete.")))
    for (test in list(...)) with(test, validate(need(f(res), msg)))
    return(res)
  }))
}
treatment_durations <- treatment_parameter('tr_dur_',
  list(f=function(res) all(res == floor(res)), msg="treatment durations not integers."),
  list(f=function(res) all(res >= 0), msg="treatment durations not positive.")
)
treatment_transmissions <- treatment_parameter('tr_rate_',
  list(f=function(res) all(res >= 0), msg="treatment rates not positive.")
)
treatment_demands <- treatment_parameter('tr_prop_',
  list(f=function(res) all((res >= 0) & (res <= 1)), msg="hospitalization proportions not in [0,1].")
)
N0 <- reactive({ input$N0 * 10^6 })
simulation_duration <- reactive({ input$simulation_duration })
```

### Model Settings Displays

```{r output_disease_params, echo=FALSE}
tabsetPanel(
  tabPanel("Incubation Distribution",
    renderPlot(plotPeriodCDF(distros$inc()))
  ),
  tabPanel("Infectious Distribution",
    renderPlot(plotPeriodCDF(distros$inf()))
  ),
  tabPanel("Introductions",
    renderPlot({
      p <- plotIntroductionScenario(introduction_scenario(), input$simulation_duration)
      p
    })
  ),
  tabPanel("Intervention Scenario",
    renderPlot({
      p <- plotInterventionScenario(intervention_scenario(), input$simulation_duration)
      p
    })
  )
)
```

```{r, echo=FALSE}
resetter <- function(infpdf, incpdf, pdf_type="manual") {
  inc_max <- length(incpdf)
  inf_max <- length(infpdf)
  updateNumericInput(session, "inf_period_max", value=inf_max)
  updateNumericInput(session, "inc_period_max", value=inc_max)
  updateRadioButtons(session, "pdf_type", selected=pdf_type)
  mapply(function(label, p) updateNumericInput(session, label, value=p),
         paste0('inc_pdf_',1:inc_max), incpdf)
  mapply(function(label, p) updateNumericInput(session, label, value=p),
       paste0('inf_pdf_',1:inf_max), infpdf)
}
with(defaults,{
  observe({
    input$reset_cdc
    resetter(inf_pdf_ref, inc_pdf_ref$cdc)
  }, priority = 0)
  observe({
    input$reset_leg
    resetter(inf_pdf_ref, inc_pdf_ref$legrand)
  }, priority = 1)
  observe({
    input$reset_eic
    resetter(inf_pdf_ref, inc_pdf_ref$eichner)
  }, priority = 2)
})
```